# Site
name: 'StarDust'
description: 'Blog of StarDust.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
url: 'dnest.github.io'
baseurl: ''
disqus: 'blog'
email: 'dnest@nate.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    ray:
      name:           Ray
      site:           https://dnest.github.io
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Ray!"
      email:          dnest@nate.com
      twitter:        https://twitter.com/dnest0

    samgil2:
      name:           Samgil2
      site:           https://dnest.github.io
      avatar:         /assets/images/avatar2.jpg
      bio:            "Cat!"
      email:          dnest@gmail.com
      twitter:        https://twitter.com/dnest0
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: ray
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]

#remote_theme : wowthemesnet/mundana-theme-jekyll
